# Generated by Django 4.1.6 on 2023-02-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_by', models.CharField(choices=[('name', 'Name'), ('date_posted', 'Upload date'), ('size', 'Size')], default='name', max_length=15)),
                ('reversed_sort', models.BooleanField(default=False)),
                ('max_capacity', models.IntegerField(default=524288000)),
                ('memory_occupied', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MediaFilter',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='files/')),
                ('name', models.CharField(default='New file', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datatype', models.CharField(default='other', max_length=10)),
                ('in_folder', models.CharField(default='other', max_length=20)),
                ('in_trash', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MediaStore',
            },
        ),
    ]
