# Generated by Django 4.1.6 on 2023-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='max_num_of_files',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='max_capacity',
            field=models.IntegerField(default=26214400),
        ),
    ]
