# Generated by Django 4.1.6 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_profiledata_max_num_of_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='num_of_files',
            field=models.IntegerField(default=0),
        ),
    ]
