# Generated by Django 4.1.4 on 2023-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_storage", "0003_file_datatype_alter_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="data",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.DeleteModel(
            name="Music",
        ),
    ]
