# Generated by Django 4.1.6 on 2023-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_alter_file_data_delete_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='New file', max_length=100),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
