# Generated by Django 4.1.6 on 2023-02-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_file_in_trash_alter_file_name_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_folder',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
