# Generated by Django 4.1.4 on 2023-02-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("phone", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=150)),
                ("birthday", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("change_date", models.DateTimeField()),
            ],
        ),
    ]
