# Generated by Django 4.1.4 on 2023-02-07 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contact_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbook",
            name="address",
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="birthday",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="change_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="description",
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="email",
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="last_name",
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name="contactbook",
            name="phone",
            field=models.CharField(default=None, max_length=25),
        ),
    ]
