# Generated by Django 4.1.4 on 2023-02-05 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contact_book", "0002_contactbook_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbook",
            name="change_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
