# Generated by Django 4.1.4 on 2023-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_book",
            "0002_alter_contactbook_address_alter_contactbook_birthday_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbook",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
