# Generated by Django 4.1.4 on 2023-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_book", "0003_alter_contactbook_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbook",
            name="email",
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
